### Nombre: Sebastián Urbina

# CC3001 Primavera 2020 Tarea 2

## Shellsort

### Profesores
Sección 1 Benjamín Bustos •
Sección 2 Jérémy Barbay •
Sección 3 Patricio Poblete / Nelson Baloian


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos una "$d$-tajada" de un arreglo como una subsecuencia de sus elementos tal que que cada uno de ellos está a $d$ casilleros de distancia del siguiente. Por ejemplo, en el siguiente diagrama se muestran en distintos colores las posible $3$-tajadas de un arreglo dado:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Noten que no todas las $d$-tajadas tienen necesariamente el mismo número de casilleros, y observen también que una "$1$-tajada" sería el arreglo completo.

Una pasada de Shellsort consiste en elegir un valor de $d$ y luego aplicar ordenación por inserción a cada $d$-tajada por separado. El arreglo resultante se dice que está "$d$-ordenado". Por ejemplo, la siguiente figura muestra el arreglo anterior una vez que ha sido $3$-ordenado:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_k,d_{k-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [4]:
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        insertar(a,k)
        
def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-1]:
        a[j]=a[j-1]
        j-=1
    a[j]=b

Probemos esto para asegurarnos que funcione bien:

In [5]:
import numpy as np

def verifica_ordenado(a):
    for i in range(0,len(a)-1):
        assert a[i]<=a[i+1]
    print("Arreglo ordenado OK.")
        
A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_ordenado(A)

[21 35 46 50 56 64 70 72 82 95]
Arreglo ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar la ordenación de una $d$-tajada

Modifique el código anterior para que en lugar de ordenar el arreglo completo, ordene solo la d-tajada que comienza en el casillero $i$:

Primero modificamos la función insertar, para que ordene los valores cada d unidades

In [6]:
def insertar2(a, k, d):
    """
    Inserta a[k] entre los elementos anteriores ubicados a d unidades
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-d] and j>=d:
        a[j]=a[j-d] #vamos ordenando los valores que están separados d unidades
        j-=d #nos movemos d espacios
    a[j]=b #posicionamos la variable recientemente almacenada

Luego la utilizamos en ordena_tajada_insercion

In [7]:
def ordena_tajada_insercion(a,i,d):
    """Ordena la d-tajada que comienza en a[i] por inserción."""
    n = len(a)
    for k in range(i, n, d): #recorremos los valores cada d unidades y vamos ordenandolos
        insertar2(a,k,d) #ordenamos los valores de la d-tajada

Pruebe aquí que su algoritmo $3$-ordena correctamente los elementos amarillos:

In [8]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_tajada_insercion(A,2,3)
print(A)

[46 35 64 21 82 70 72 56 95 50]


## 2) Programar una pasada de Shellsort

A continuación programe una función que haga una pasada de Shellsort, dado un arreglo $a$ y el valor de $d$. Esta función debe aplicar ``ordena_tajada_inserción`` sobre cada una de las $d$-tajadas de $a$. 

In [9]:
def pasada_Shellsort(a,d):
    """Hace una pasada de Shellsort"""
    for i in range(d): #todas las posibles d-tajadas
        ordena_tajada_insercion(a,i,d)

Luego pruebe esto y comprueba que da el mismo resultado que el ejemplo más arriba:

In [10]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
pasada_Shellsort(A,3)
print(A)

[21 35 64 46 56 70 50 82 95 72]


## 3) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_k=2^k-1$, esto es: $\ldots, 63, 31, 15, 7, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$:

In [11]:
def Shellsort(a):
    """Ordena a usando Shell Sort, con la secuencia de valores …,63,31,15,7,3,1"""
    if len(a) == 0: #caso borde
        return a
    k = int(np.log2(len(a))) #La máxima potencia a la cual obtener los valores de d para no salirnos del arreglo,
    dk = [2**i-1 for i in range(k,0,-1)] #creamos la secuencia de valores
    for d in dk:
        pasada_Shellsort(a,d)

Pruebe aquí su algoritmo de la manera siguiente:

In [12]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
Shellsort(A)
print(A)
verifica_ordenado(A)

[21 35 46 50 56 64 70 72 82 95]
Arreglo ordenado OK.


En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

In [13]:
A_r = np.random.randint(1000,size = 1000) #arreglo de tamaño 1000, con valores al azar entre 0 y 1000
Shellsort(A_r)
verifica_ordenado(A_r)

Arreglo ordenado OK.


## 4) Probar con una secuencia diferente de valores $d_k$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_k$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

Ahora utilizaremos los incrementos de Shell, que comienzan con n/2, y se dividen en 2 cada vez hasta llegar a 1, con n el largo del arreglo. Utilizando estos incrementos, ShellSort en el peor caso funciona en tiempo $\Theta(n^{2})$.

Referencia: https://es.wikipedia.org/wiki/Ordenamiento_Shell

In [14]:
def Shellsort2(a):
    """Ordena a usando Shell Sort, con la secuencia de valores de shell, n/2, n/4, n/8,.., 1, con n largo del arreglo"""
    d = len(a)//2
    while d >= 1:
        pasada_Shellsort(a,d)
        d = d//2

Hacemos una prueba

In [15]:
A_r2 = np.random.randint(1000,size = 1000) #arreglo de tamaño 1000, con valores al azar entre 0 y 1000
Shellsort2(A_r2)
verifica_ordenado(A_r2)

Arreglo ordenado OK.
